defaults:
  max_columns: 360
  terminal_font_size: 18
options:
  list_item_newlines: 1
  # whether slides are automatically terminated when a slide title is found.
  implicit_slide_ends: false
  # show all lists incrementally, by implicitly adding pauses in between elements.
  incremental_lists: false
  # this option tells presenterm you don't care about extra parameters in
  # presentation's front matter. This can be useful if you're trying to load a
  # presentation made for another tool
  strict_front_matter_parsing: true
  auto_render_languages:
    - mermaid
    - latex
